spring:
  application:
  name: polyclinic
doc:
  specialization:
    doc1: Cтоматолог
    doc2: Хирург
    doc3: Терапевт
  price:
    dentist: 1500
    therapist: 500
    junior-surgeon: 700
    senior-surgeon: 2000

